import type { Metadata } from 'next';
import './globals.css';
import { SnackBar } from '@/components/common/snackbar';
import { NextTopLoader } from '@/components/common/next-loading';
import { Background } from '@/components/common/background';
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} text-dark-gray-05 antialiased`}>
        <Background />
        <div className="relative z-10">{children}</div>
        <SnackBar />
        <NextTopLoader />
      </body>
    </html>
  );
}
